# Generated by Django 2.0.1 on 2018-03-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job_position', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('campus', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('ict_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
